#!/usr/bin/env bash

# Configure the mosquitto broker so other machines (e.g. Home Assistant) can
# reach it.
#
# The packaged Debian config binds to loopback only, so nothing off-Pi can
# connect. This writes a drop-in rather than editing mosquitto.conf, so a
# package upgrade cannot silently clobber it and so `uninstall.sh` has one
# file to remove.
#
# Two listeners are configured on the same port:
#   * loopback, so mqtt.py on this Pi keeps working
#   * the remote address, which defaults to this machine's Tailscale IP
# A single remote listener would be a trap: mosquitto replaces the implicit
# loopback listener as soon as any `listener` is defined, so mqtt.py would
# lose its own broker.
#
# Authentication is required (allow_anonymous false) and the credentials are
# read from .env, which stays the single source of truth shared with mqtt.py.
# The password is piped to mosquitto_passwd on stdin so it never appears in
# `ps` output or the shell history.
#
# Usage: sudo scripts/install-mqtt-broker.sh

set -euo pipefail

GOE_PATH="$(realpath "$(dirname "$(readlink -e "$0")")/..")"
CONF_FILE=/etc/mosquitto/conf.d/20-gardyn-remote.conf
PASSWD_FILE=/etc/mosquitto/passwd
ENV_FILE="${GOE_PATH}/.env"

if [ "$(id -u)" -ne 0 ]; then
    echo "This writes to /etc/mosquitto and needs sudo." >&2
    echo "Usage: sudo $0" >&2
    exit 1
fi

if ! command -v mosquitto >/dev/null 2>&1; then
    echo "mosquitto is not installed. Run: sudo apt-get install -y mosquitto" >&2
    exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
    echo "Missing $ENV_FILE; copy .env-dist and fill it in." >&2
    exit 1
fi

# Read KEY from .env, tolerating quotes and surrounding whitespace.
env_get() {
    sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" |
        head -1 | sed -e 's/^["'"'"']//' -e 's/["'"'"']$//' -e 's/[[:space:]]*$//'
}

MQTT_USER="$(env_get MQTT_USERNAME)"
MQTT_PASS="$(env_get MQTT_PASSWORD)"
MQTT_PORT="$(env_get MQTT_PORT)"
MQTT_PORT="${MQTT_PORT:-1883}"

if [ -z "$MQTT_USER" ] || [ -z "$MQTT_PASS" ]; then
    echo "MQTT_USERNAME and MQTT_PASSWORD must both be set in .env" >&2
    exit 1
fi

# The shipped example value is not a secret. Creating an account whose
# password is published in the README would be worse than not configuring auth.
case "$MQTT_PASS" in
    somepassword|password|changeme|secret)
        echo "Refusing to run: MQTT_PASSWORD in .env is still the example value" >&2
        echo "Set a real password first, e.g.  openssl rand -base64 18" >&2
        exit 1
        ;;
esac

if [ ${#MQTT_PASS} -lt 12 ]; then
    echo "Warning: MQTT_PASSWORD is only ${#MQTT_PASS} characters; 12+ is recommended." >&2
fi

# Prefer the tailnet address: reachable from other devices without exposing
# the broker to everything on the home LAN.
REMOTE_BIND="${MQTT_BIND:-}"
if [ -z "$REMOTE_BIND" ]; then
    REMOTE_BIND="$(ip -4 -o addr show tailscale0 2>/dev/null | awk '{split($4,a,"/"); print a[1]; exit}')"
fi
if [ -z "$REMOTE_BIND" ]; then
    REMOTE_BIND=0.0.0.0
    echo "No Tailscale address found; falling back to 0.0.0.0 (reachable by" >&2
    echo "everything on the LAN). Set MQTT_BIND to restrict this." >&2
fi

conf_tmp=$(mktemp)
trap 'rm -f "$conf_tmp"' EXIT

cat > "$conf_tmp" <<EOF
# Generated by scripts/install-mqtt-broker.sh -- edit there, not here.
# Regenerate with: sudo scripts/install-mqtt-broker.sh

allow_anonymous false
password_file $PASSWD_FILE

# Loopback: mqtt.py on this machine.
listener $MQTT_PORT 127.0.0.1

# Remote clients (Home Assistant).
listener $MQTT_PORT $REMOTE_BIND
EOF

# Password file. -c creates or truncates, so the user is set to the current
# .env value every run rather than accumulating stale accounts.
printf '%s\n%s\n' "$MQTT_PASS" "$MQTT_PASS" | mosquitto_passwd -c "$PASSWD_FILE" "$MQTT_USER" >/dev/null
if getent group mosquitto >/dev/null; then
    chown root:mosquitto "$PASSWD_FILE"
fi
chmod 0640 "$PASSWD_FILE"

install -m 644 "$conf_tmp" "$CONF_FILE"

systemctl restart mosquitto
sleep 1

if ! systemctl is-active --quiet mosquitto; then
    echo "mosquitto failed to start; rolling back to the packaged config." >&2
    rm -f "$CONF_FILE"
    systemctl restart mosquitto
    echo "Rolled back -- the broker is back on loopback only." >&2
    exit 1
fi

systemctl restart mqtt.service 2>/dev/null || true

echo
echo "Broker configured."
echo "  user:     $MQTT_USER"
echo "  listening on 127.0.0.1:$MQTT_PORT and $REMOTE_BIND:$MQTT_PORT"
echo
echo "Test from another machine on the same network as $REMOTE_BIND:"
echo "  mosquitto_sub -h $REMOTE_BIND -p $MQTT_PORT -u $MQTT_USER -P '<password>' -t 'gardyn/#' -v"
echo
echo "Confirm mqtt.py reconnected:"
echo "  journalctl -u mqtt.service -n 20 --no-pager"
echo
echo "To undo: sudo rm $CONF_FILE && sudo systemctl restart mosquitto"